import { exportVideo } from "./export";
import { getActiveTemplate, type EffectOptions } from "./templates";
import { initBrandKitPanel } from "./brand-kit";
import "./styles.css";

// --- Types ---
interface FrameData {
  time: number;
  x: number; // 0-1 normalized crop position (computed from keyframes)
  bitmap: ImageBitmap;
  skipped: boolean;
}

interface Keyframe {
  time: number;
  x: number; // 0-1 normalized position
  auto: boolean; // true = generated by motion detection, false = user-placed
}

// --- State ---
let videoEl: HTMLVideoElement | null = null;
let frames: FrameData[] = [];
let keyframes: Keyframe[] = [];
let currentIdx = 0;
let skipRanges: { start: number; end: number }[] = [];
let markStartTime: number | null = null;
let dragging = false;

const $ = (id: string) => document.getElementById(id)!;

// --- Session persistence (IndexedDB for video, localStorage for edits) ---
interface SavedSession {
  fileName: string;
  fileSize: number;
  keyframes: Keyframe[];
  skipRanges: { start: number; end: number }[];
  numSamples: number;
}

const DB_NAME = "vr-storage";
const DB_STORE = "videos";

function openDB(): Promise<IDBDatabase> {
  return new Promise((resolve, reject) => {
    const req = indexedDB.open(DB_NAME, 1);
    req.onupgradeneeded = () => req.result.createObjectStore(DB_STORE);
    req.onsuccess = () => resolve(req.result);
    req.onerror = () => reject(req.error);
  });
}

async function saveVideoToDB(file: File): Promise<void> {
  const db = await openDB();
  const tx = db.transaction(DB_STORE, "readwrite");
  tx.objectStore(DB_STORE).put(file, "current-video");
  await new Promise<void>((resolve, reject) => {
    tx.oncomplete = () => resolve();
    tx.onerror = () => reject(tx.error);
  });
  db.close();
}

async function loadVideoFromDB(): Promise<File | null> {
  try {
    const db = await openDB();
    const tx = db.transaction(DB_STORE, "readonly");
    const req = tx.objectStore(DB_STORE).get("current-video");
    const result = await new Promise<File | null>((resolve) => {
      req.onsuccess = () => resolve(req.result ?? null);
      req.onerror = () => resolve(null);
    });
    db.close();
    return result;
  } catch { return null; }
}

async function clearVideoDB(): Promise<void> {
  try {
    const db = await openDB();
    const tx = db.transaction(DB_STORE, "readwrite");
    tx.objectStore(DB_STORE).delete("current-video");
    await new Promise<void>((resolve) => { tx.oncomplete = () => resolve(); });
    db.close();
  } catch { /* ignore */ }
}

function saveSession(file: File) {
  const session: SavedSession = {
    fileName: file.name,
    fileSize: file.size,
    keyframes,
    skipRanges,
    numSamples: frames.length,
  };
  localStorage.setItem("vr-session", JSON.stringify(session));
  saveVideoToDB(file);
}

function loadSession(): SavedSession | null {
  const raw = localStorage.getItem("vr-session");
  if (!raw) return null;
  try { return JSON.parse(raw); } catch { return null; }
}

function clearSession() {
  localStorage.removeItem("vr-session");
  clearVideoDB();
}

// --- Upload ---
let currentFile: File | null = null;
let restoreSession = false;

async function loadVideo(file: File, shouldRestore: boolean): Promise<void> {
  restoreSession = shouldRestore;
  currentFile = file;
  videoEl = document.createElement("video");
  videoEl.muted = true;
  videoEl.playsInline = true;
  videoEl.preload = "auto";
  videoEl.src = URL.createObjectURL(file);
  await new Promise((r) =>
    videoEl!.addEventListener("loadeddata", r, { once: true })
  );

  $("fileStatus").textContent = `${videoEl.videoWidth}x${videoEl.videoHeight} · ${videoEl.duration.toFixed(1)}s · ${(file.size / 1024 / 1024).toFixed(1)}MB`;
  $("fileStatus").className = "status success";
  $("analyzeCard").classList.remove("hidden");
  $("clearBtn").classList.remove("hidden");
}

// Auto-restore video from IndexedDB on page load
(async () => {
  const saved = loadSession();
  const storedFile = await loadVideoFromDB();
  if (saved && storedFile && saved.fileName === storedFile.name) {
    await loadVideo(storedFile, true);

    // If we have saved edits (keyframes/skipRanges), auto-run analyze to restore state
    if (saved.keyframes.length > 0) {
      ($("analyzeBtn") as HTMLButtonElement).click();
    }
  }
})();

$("fileInput").addEventListener("change", async (e) => {
  const file = (e.target as HTMLInputElement).files?.[0];
  if (!file) return;

  // Auto-restore session if same file re-uploaded
  const saved = loadSession();
  const shouldRestore = !!(saved && saved.fileName === file.name && saved.fileSize === file.size);
  if (!shouldRestore) clearSession();

  await loadVideo(file, shouldRestore);
});

// Clear button — reset everything
$("clearBtn").addEventListener("click", () => {
  clearSession();
  currentFile = null;
  videoEl = null;
  frames = [];
  keyframes = [];
  skipRanges = [];
  currentIdx = 0;
  markStartTime = null;

  // Hide all cards except upload
  $("analyzeCard").classList.add("hidden");
  $("editCard").classList.add("hidden");
  $("exportCard").classList.add("hidden");
  $("resultCard").classList.add("hidden");
  $("clearBtn").classList.add("hidden");
  $("fileStatus").textContent = "";
  $("fileStatus").className = "status";
  ($("fileInput") as HTMLInputElement).value = "";
});

// --- Analyze (motion detection) ---
$("analyzeBtn").addEventListener("click", async () => {
  if (!videoEl) return;
  ($("analyzeBtn") as HTMLButtonElement).disabled = true;
  $("analyzeStatus").textContent = "Detecting motion...";

  const duration = videoEl.duration;
  const numSamples = Math.min(200, Math.round(duration * 3));
  const step = duration / numSamples;

  // Detect motion
  const positions = await detectMotion(videoEl, numSamples);
  const smoothed = smoothPositions(positions);

  // Build keyframes from smoothed positions (keep only significant changes)
  keyframes = [];
  const keyframeThreshold = 0.03; // minimum position change to create a new keyframe
  keyframes.push({ time: 0, x: smoothed[0]?.x ?? 0.5, auto: true });
  for (let i = 1; i < smoothed.length; i++) {
    const lastKf = keyframes[keyframes.length - 1]!;
    const curr = smoothed[i]!;
    if (Math.abs(curr.x - lastKf.x) > keyframeThreshold) {
      keyframes.push({ time: curr.time, x: curr.x, auto: true });
    }
  }
  // Always include last position
  const lastSmoothed = smoothed[smoothed.length - 1]!;
  if (keyframes[keyframes.length - 1]!.time < lastSmoothed.time) {
    keyframes.push({ time: lastSmoothed.time, x: lastSmoothed.x, auto: true });
  }

  // Restore saved session if user chose to
  if (restoreSession) {
    const saved = loadSession();
    if (saved) {
      keyframes = saved.keyframes;
      skipRanges = saved.skipRanges;
    }
    restoreSession = false;
  }

  // Extract thumbnails and build frame data
  $("analyzeStatus").textContent = "Building filmstrip...";
  const thumbW = 36 * 2;
  const thumbH = 64 * 2;
  const canvas = document.createElement("canvas");
  canvas.width = thumbW;
  canvas.height = thumbH;
  const ctx = canvas.getContext("2d")!;

  frames = [];
  for (let i = 0; i < numSamples; i++) {
    const frameTime = i * step;
    videoEl.currentTime = frameTime;
    await new Promise((r) =>
      videoEl!.addEventListener("seeked", r, { once: true })
    );

    // Get interpolated position from keyframes
    const x = getPositionAtTime(frameTime, duration);

    // Draw 9:16 crop region as thumbnail
    const cropW = videoEl.videoHeight * (9 / 16);
    const maxX = videoEl.videoWidth - cropW;
    const srcX = maxX * x;
    ctx.drawImage(videoEl, srcX, 0, cropW, videoEl.videoHeight, 0, 0, thumbW, thumbH);
    const bitmap = await createImageBitmap(canvas);

    frames.push({
      time: frameTime,
      x,
      bitmap,
      skipped: false,
    });

    ($("analyzeProgress") as HTMLElement).style.width =
      Math.round(((i + 1) / numSamples) * 100) + "%";
  }

  $("analyzeStatus").textContent = `${numSamples} frames analyzed`;
  $("analyzeStatus").className = "status success";

  // Show editor
  $("editorCard").classList.remove("hidden");
  $("exportCard").classList.remove("hidden");
  renderFilmstrip();
  goToFrame(0);
  renderSkipBar();
});

// --- Filmstrip ---
function renderFilmstrip() {
  const container = $("filmstrip");
  container.innerHTML = "";

  for (let i = 0; i < frames.length; i++) {
    const div = document.createElement("div");
    div.className = "thumb";
    if (i === currentIdx) div.classList.add("active");
    if (frames[i]!.skipped) div.classList.add("skipped");

    // Mark frames that have a keyframe (user-placed get a different indicator)
    const kf = keyframes.find((k) => Math.abs(k.time - frames[i]!.time) < 0.1);
    if (kf && !kf.auto) div.classList.add("keyframe-user");
    else if (kf) div.classList.add("keyframe-auto");

    const c = document.createElement("canvas");
    c.width = 36 * 2;
    c.height = 64 * 2;
    c.getContext("2d")!.drawImage(frames[i]!.bitmap, 0, 0);
    div.appendChild(c);
    div.addEventListener("click", () => goToFrame(i));
    container.appendChild(div);
  }
}

function goToFrame(idx: number) {
  if (idx < 0 || idx >= frames.length || !videoEl) return;
  currentIdx = idx;

  // Update filmstrip active
  document.querySelectorAll(".filmstrip .thumb").forEach((el, i) => {
    el.classList.toggle("active", i === idx);
  });

  // Scroll into view
  const thumbs = document.querySelectorAll(".filmstrip .thumb");
  thumbs[idx]?.scrollIntoView({ behavior: "smooth", block: "nearest", inline: "center" });

  // Draw source frame with crop overlay
  drawCropEditor();

  // Update info
  const f = frames[idx]!;
  $("frameCounter").textContent = `Frame ${idx + 1} / ${frames.length}`;
  $("frameTime").textContent = formatTime(f.time);

  // Show/hide delete keyframe button
  const userKf = keyframes.find(
    (k) => !k.auto && Math.abs(k.time - f.time) < 0.1
  );
  const delBtn = $("deleteKeyframeBtn") as HTMLElement;
  delBtn.style.display = userKf ? "inline-flex" : "none";
}

async function drawCropEditor() {
  if (!videoEl) return;
  const f = frames[currentIdx]!;

  videoEl.currentTime = f.time;
  await new Promise((r) =>
    videoEl!.addEventListener("seeked", r, { once: true })
  );

  // Source canvas
  const srcCanvas = $("sourceCanvas") as HTMLCanvasElement;
  srcCanvas.width = videoEl.videoWidth;
  srcCanvas.height = videoEl.videoHeight;
  srcCanvas.getContext("2d")!.drawImage(videoEl, 0, 0);

  // Position crop region overlay
  const cropW = videoEl.videoHeight * (9 / 16);
  const maxX = videoEl.videoWidth - cropW;
  const cropLeft = maxX * f.x;
  const container = $("cropContainer");
  const displayScale = container.clientWidth / videoEl.videoWidth;
  const region = $("cropRegion") as HTMLElement;
  region.style.width = cropW * displayScale + "px";
  region.style.left = cropLeft * displayScale + "px";

  // Result canvas (9:16 preview)
  const resCanvas = $("resultCanvas") as HTMLCanvasElement;
  const resH = 180;
  const resW = resH * (9 / 16);
  resCanvas.width = resW;
  resCanvas.height = resH;
  resCanvas.getContext("2d")!.drawImage(
    videoEl, cropLeft, 0, cropW, videoEl.videoHeight,
    0, 0, resW, resH
  );
}

// --- Drag crop editing ---
function setupCropDrag() {
  const region = $("cropRegion");
  const container = $("cropContainer");
  let startX = 0;
  let startPos = 0;

  function onStart(clientX: number) {
    dragging = true;
    startX = clientX;
    startPos = frames[currentIdx]!.x;
  }

  function onMove(clientX: number) {
    if (!dragging || !videoEl) return;
    const containerW = container.clientWidth;
    const dx = clientX - startX;
    const dxNorm = dx / containerW;
    const newX = Math.max(0, Math.min(1, startPos + dxNorm));
    frames[currentIdx]!.x = newX;
    drawCropEditor();
  }

  function onEnd() {
    if (dragging) {
      // Create/update a user keyframe at this frame's time
      const f = frames[currentIdx]!;
      addOrUpdateKeyframe(f.time, f.x, false);
      renderFilmstrip();
    }
    dragging = false;
  }

  region.addEventListener("mousedown", (e) => { e.preventDefault(); onStart(e.clientX); });
  window.addEventListener("mousemove", (e) => onMove(e.clientX));
  window.addEventListener("mouseup", onEnd);

  region.addEventListener("touchstart", (e) => { e.preventDefault(); onStart(e.touches[0]!.clientX); });
  window.addEventListener("touchmove", (e) => { if (dragging) onMove(e.touches[0]!.clientX); });
  window.addEventListener("touchend", onEnd);

  // Click on source canvas to reposition
  container.addEventListener("click", (e) => {
    if (dragging) return;
    const rect = container.getBoundingClientRect();
    const newX = Math.max(0, Math.min(1, (e.clientX - rect.left) / rect.width));
    frames[currentIdx]!.x = newX;
    addOrUpdateKeyframe(frames[currentIdx]!.time, newX, false);
    drawCropEditor();
    renderFilmstrip();
  });
}

// --- Skip ranges ---
$("markStartBtn").addEventListener("click", () => {
  markStartTime = frames[currentIdx]!.time;
  $("markStartBtn").textContent = `Start: ${markStartTime.toFixed(1)}s ✓`;
});

$("markEndBtn").addEventListener("click", () => {
  const endTime = frames[currentIdx]!.time;
  if (markStartTime === null || endTime <= markStartTime) return;

  skipRanges.push({ start: markStartTime, end: endTime });
  markStartTime = null;
  $("markStartBtn").textContent = "Mark Start";
  applySkipRanges();
  renderSkipBar();
  renderFilmstrip();
  if (currentFile) saveSession(currentFile);
});

$("undoSkipBtn").addEventListener("click", () => {
  skipRanges.pop();
  applySkipRanges();
  renderSkipBar();
  renderFilmstrip();
  if (currentFile) saveSession(currentFile);
});

function applySkipRanges() {
  for (const f of frames) {
    f.skipped = skipRanges.some((r) => f.time >= r.start && f.time < r.end);
  }
}

function renderSkipBar() {
  const container = $("skipBar");
  container.innerHTML = "";

  if (!videoEl) return;
  const duration = videoEl.duration;
  const sorted = [...skipRanges].sort((a, b) => a.start - b.start);

  let pos = 0;
  for (const range of sorted) {
    if (range.start > pos) {
      const seg = document.createElement("div");
      seg.className = "seg keep";
      seg.style.width = ((range.start - pos) / duration) * 100 + "%";
      container.appendChild(seg);
    }
    const seg = document.createElement("div");
    seg.className = "seg skip";
    seg.style.width = ((range.end - range.start) / duration) * 100 + "%";
    container.appendChild(seg);
    pos = range.end;
  }
  if (pos < duration) {
    const seg = document.createElement("div");
    seg.className = "seg keep";
    seg.style.width = ((duration - pos) / duration) * 100 + "%";
    container.appendChild(seg);
  }

  // Stats
  const skipTotal = skipRanges.reduce((sum, r) => sum + (r.end - r.start), 0);
  $("skipStats").textContent = skipRanges.length > 0
    ? `${skipRanges.length} cut${skipRanges.length > 1 ? "s" : ""} · ${skipTotal.toFixed(1)}s skipped · ${(duration - skipTotal).toFixed(1)}s output`
    : "";
}

// --- Export ---
$("exportBtn").addEventListener("click", async () => {
  if (!videoEl) return;
  if (!("VideoEncoder" in window)) {
    $("exportStatus").textContent =
      "Export unavailable: this browser doesn't support WebCodecs.";
    $("exportStatus").className = "status error";
    return;
  }

  ($("exportBtn") as HTMLButtonElement).disabled = true;
  $("exportStatus").textContent = "Encoding...";
  const totalStart = performance.now();

  // Read export options from UI
  const durationVal = parseInt(($("exportDuration") as HTMLSelectElement).value, 10);
  const effects: EffectOptions = {
    intro: ($("effectIntro") as HTMLInputElement).checked,
    lowerThird: ($("effectLowerThird") as HTMLInputElement).checked,
    watermark: ($("effectWatermark") as HTMLInputElement).checked,
  };

  const template = await getActiveTemplate(effects);

  try {
    const blob = await exportVideo({
      videoEl,
      keyframes,
      skipRanges,
      overlay: template.render,
      maxDuration: durationVal || undefined,
      onProgress: (pct) => {
        ($("exportProgress") as HTMLElement).style.width = pct + "%";
        $("exportStatus").textContent = `Encoding... ${pct}%`;
      },
    });

    template.dispose();

    ($("exportProgress") as HTMLElement).style.width = "100%";
    const totalTime = ((performance.now() - totalStart) / 1000).toFixed(1);
    $("exportStatus").textContent = "Done!";
    $("exportStatus").className = "status success";

    const url = URL.createObjectURL(blob);
    ($("outputVideo") as HTMLVideoElement).src = url;
    $("metricSize").textContent = (blob.size / 1024 / 1024).toFixed(1) + "MB";
    $("metricTotal").textContent = totalTime + "s";
    const encW = Math.min(1080, Math.round(videoEl.videoHeight * (9 / 16)));
    const encH = Math.min(1920, videoEl.videoHeight);
    $("metricRes").textContent = `${encW - (encW % 2)}x${encH - (encH % 2)}`;
    $("resultCard").classList.remove("hidden");
    $("downloadBtn").onclick = () => {
      const a = document.createElement("a");
      a.href = url;
      a.download = "reframed_9x16.mp4";
      a.click();
    };
  } catch (err) {
    template.dispose();
    $("exportStatus").textContent = `Export failed: ${err instanceof Error ? err.message : "Unknown error"}`;
    $("exportStatus").className = "status error";
  } finally {
    ($("exportBtn") as HTMLButtonElement).disabled = false;
  }
});

// --- Helpers ---

function getPositionAtTime(time: number, _duration: number): number {
  if (keyframes.length === 0) return 0.5;
  if (keyframes.length === 1) return keyframes[0]!.x;

  // Before first keyframe
  if (time <= keyframes[0]!.time) return keyframes[0]!.x;
  // After last keyframe
  if (time >= keyframes[keyframes.length - 1]!.time) return keyframes[keyframes.length - 1]!.x;

  // Find surrounding keyframes and interpolate
  for (let i = 0; i < keyframes.length - 1; i++) {
    const a = keyframes[i]!;
    const b = keyframes[i + 1]!;
    if (time >= a.time && time <= b.time) {
      const t = (time - a.time) / (b.time - a.time);
      return a.x * (1 - t) + b.x * t;
    }
  }
  return keyframes[keyframes.length - 1]!.x;
}

function recomputeFramePositions() {
  if (!videoEl) return;
  const duration = videoEl.duration;
  for (const f of frames) {
    f.x = getPositionAtTime(f.time, duration);
  }
}

function addOrUpdateKeyframe(time: number, x: number, auto = false) {
  // Find existing keyframe within 0.1s tolerance
  const existing = keyframes.find((k) => Math.abs(k.time - time) < 0.1);
  if (existing) {
    existing.x = x;
    existing.auto = auto;
  } else {
    keyframes.push({ time, x, auto });
    keyframes.sort((a, b) => a.time - b.time);
  }
  recomputeFramePositions();
  if (currentFile) saveSession(currentFile);
}

function removeKeyframe(time: number) {
  const idx = keyframes.findIndex((k) => Math.abs(k.time - time) < 0.1);
  if (idx !== -1 && keyframes.length > 1) {
    keyframes.splice(idx, 1);
    recomputeFramePositions();
    if (currentFile) saveSession(currentFile);
  }
}

async function detectMotion(
  video: HTMLVideoElement,
  n: number
): Promise<{ time: number; x: number }[]> {
  const pos: { time: number; x: number }[] = [];
  const step = video.duration / n;
  const dw = 160;
  const dh = Math.round(160 * (video.videoHeight / video.videoWidth));
  const c = document.createElement("canvas");
  c.width = dw;
  c.height = dh;
  const ctx = c.getContext("2d", { willReadFrequently: true })!;
  let prev: ImageData | null = null;

  for (let i = 0; i < n; i++) {
    video.currentTime = i * step;
    await new Promise((r) =>
      video.addEventListener("seeked", r, { once: true })
    );
    ctx.drawImage(video, 0, 0, dw, dh);
    const d = ctx.getImageData(0, 0, dw, dh);

    if (prev) {
      let sx = 0;
      let cnt = 0;
      const totalPixels = dw * dh;
      for (let y = 0; y < dh; y++) {
        for (let x = 0; x < dw; x++) {
          const idx = (y * dw + x) * 4;
          const diff =
            Math.abs((d.data[idx] ?? 0) - (prev.data[idx] ?? 0)) +
            Math.abs((d.data[idx + 1] ?? 0) - (prev.data[idx + 1] ?? 0)) +
            Math.abs((d.data[idx + 2] ?? 0) - (prev.data[idx + 2] ?? 0));
          if (diff > 60) {
            sx += x;
            cnt++;
          }
        }
      }
      const panThreshold = 0.6;
      const isPan = cnt / totalPixels > panThreshold;
      const lastGood = pos[pos.length - 1]?.x ?? 0.5;

      if (isPan) {
        // Whole-frame pan: centroid is meaningless, carry forward last good position
        pos.push({ time: i * step, x: lastGood });
      } else {
        pos.push({
          time: i * step,
          x: cnt > 50 ? sx / cnt / dw : lastGood,
        });
      }
    } else {
      pos.push({ time: 0, x: 0.5 });
    }

    prev = d;
    ($("analyzeProgress") as HTMLElement).style.width =
      Math.round((i / n) * 100) + "%";
  }
  return pos;
}

function smoothPositions(
  p: { time: number; x: number }[],
  w = 5
): { time: number; x: number }[] {
  return p.map((v, i) => {
    const s = Math.max(0, i - Math.floor(w / 2));
    const e = Math.min(p.length, i + Math.ceil(w / 2));
    return {
      time: v.time,
      x: p.slice(s, e).reduce((a, b) => a + b.x, 0) / (e - s),
    };
  });
}

function formatTime(s: number): string {
  const m = Math.floor(s / 60);
  const sec = (s % 60).toFixed(1);
  return `${m}:${sec.padStart(4, "0")}`;
}

// --- Play preview ---
let playing = false;

$("playPreviewBtn").addEventListener("click", async () => {
  if (playing) {
    playing = false;
    $("playPreviewBtn").textContent = "▶ Play";
    return;
  }

  playing = true;
  $("playPreviewBtn").textContent = "⏸ Stop";

  const startIdx = currentIdx;
  for (let i = startIdx; i < frames.length && playing; i++) {
    if (frames[i]!.skipped) continue;
    goToFrame(i);
    await drawCropEditor();
    // ~10fps playback
    await new Promise((r) => setTimeout(r, 100));
  }

  playing = false;
  $("playPreviewBtn").textContent = "▶ Play";
});

// --- Keyboard navigation ---
document.addEventListener("keydown", (e) => {
  if (!$("editorCard").classList.contains("hidden")) {
    if (e.key === "ArrowLeft") {
      let next = currentIdx - 1;
      while (next >= 0 && frames[next]!.skipped) next--;
      if (next >= 0) goToFrame(next);
    }
    if (e.key === "ArrowRight") {
      let next = currentIdx + 1;
      while (next < frames.length && frames[next]!.skipped) next++;
      if (next < frames.length) goToFrame(next);
    }
  }
});

// Init drag on load
setupCropDrag();

// Init brand kit settings panel
initBrandKitPanel();

// Delete keyframe button
$("deleteKeyframeBtn").addEventListener("click", () => {
  const f = frames[currentIdx]!;
  removeKeyframe(f.time);
  renderFilmstrip();
  goToFrame(currentIdx);
});
